### ISSUE TITLE
Support slice data type for property in request object

### ISSUE THREAD

**Issue by ngdinhtoan** [sergei-svistunov/gorpc#13]
In some requests, a slice of a struct in request object is required.
But, `gorpc` doesn't support it now:

    panic: Type slice does not supported by handler /xyz for version number 1

Please support slice in request object.

**Comment by nordligulv** [comment]
gorpc uses query arguments that's why parameters have to be "flat" (simple types not structs).
How do you propose to encode structs to a query?

**Comment by nordligulv** [comment]
I guess this type of request can be done as explained in issue #9 
What do you think?

**Comment by ngdinhtoan** [comment]
I see now, thank you.
Waiting for #9.
