### ISSUE TITLE
Handler should be able to define request URI

### ISSUE THREAD

**Issue by ngdinhtoan** [sergei-svistunov/gorpc#14]
`gorpc` is using package path of handler to register URI for handler.
That mean if want to have `/get_something_by_something_else` request URI, then package name for the handler must be `get_something_by_something_else`, and perhaps the folder name also must be same that.

I know that it still works, but it isn't recommended in GO.

I think the handler should be able to define URI request that it can handle.
In case handler don't define URI, okie package path can be accepted.

**Comment by nordligulv** [comment]
gorpc uses versioned handlers "by design" only so in your case it would be ```get_something_by_something_else``` package and v1.go file with version 1 of your handler.
The URI path of the handler would be ```/get_something_by_something_else/v1/```

Please correct me if I missed something in your explanation.

**Comment by savalin** [comment]
I think @ngdinhtoan  means that 'get_something_by_something_else' is not valid package name in GO and for this case he suggest to use some config to define other URI path for package to escape long_ugly_package_names.

**Comment by ngdinhtoan** [comment]
that's what I meant.

**Comment by sergei-svistunov** [comment]
@ngdinhtoan, I've done it consciously. It is very useful when interface is the same as project structure. You write only packages and don't think about transport and routing. 
How do you want name package for handler `get_something_by_something_else`?

**Comment by ngdinhtoan** [comment]
My point is just want to make package name and folder name shorten.

For example, if we have some handlers for `get_product_by_name` and `get_product_by_id`,
we can have package `handler/product` and `product.GetByName()` will return handler for request uri `get_product_by_name`  and `product.GetByID()` will return handler for request uri `get_product_by_id`.

BTW, it's just my opinion ;)

**Comment by sergei-svistunov** [comment]
Where are handlers' versions, handlers' description, in/out parameters definitions for each version? It will be ugly mesh If you mix it in one package.
