### ISSUE TITLE
Make error processing attacheable as middleware

### ISSUE THREAD

**Issue by elgris** [sergei-svistunov/gorpc#3]
Following code from `transport/http_json/http_json.go:47` processes panics
```
	defer func() {
		if r := recover(); r != nil {
			trace := make([]byte, 1024)
			n := runtime.Stack(trace, false)
			trace = trace[:n]

			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		}
	}()
```

Usually this logic is handled by middleware. Let's move it to middleware layer, because more of them  will come for sure (SecurityMiddleware is one of them)

**Comment by sergei-svistunov** [comment]
@savalin has added callback https://github.com/sergei-svistunov/gorpc/blob/master/transport/http_json/http_json.go#L54
Now you can do some extra actions on panic.
